# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_item_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='first_app.Item'),
        ),
    ]
