# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20170531_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='item',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='item',
            field=models.ManyToManyField(related_name='wishlists', to='first_app.Item'),
        ),
    ]
